"""Core: configuration, exceptions, telemetry, state management, expression parsing."""

from formalconstruct.core.config import AxleConfig, PipelineConfig, RepairBudget
from formalconstruct.core.exceptions import (
    AxleConnectionError,
    AxleConnectionResetError,
    AxleError,
    AxleInvalidArgumentError,
    AxleNonTransientError,
    AxleRateLimitedError,
    AxleRetriesExhaustedError,
    AxleTimeoutError,
    AxleTransientError,
    AxleUnavailableError,
    AxleValidationError,
    BudgetExhaustedError,
    ExpressionParseError,
    FormalConstructError,
    MissingApiKeyError,
    ScaffoldingError,
    SchemaExtractionError,
    SchemaRollbackRequested,
    UnknownDomainError,
    UnsupportedCompositionError,
    UnsupportedDomainError,
)
from formalconstruct.core.expression_parser import (
    BinOp,
    ExprNode,
    ExpressionParser,
    FuncApp,
    Ident,
    NumberLit,
    UnaryNeg,
    emit_lean,
)
from formalconstruct.core.state_manager import StateManager
from formalconstruct.core.telemetry import (
    log_axle_call,
    log_phase_duration,
    log_repair_stats,
    log_termination,
    sanitize_log_value,
    timed,
)

__all__ = [
    "AxleConfig",
    "PipelineConfig",
    "RepairBudget",
    "BinOp",
    "ExprNode",
    "ExpressionParser",
    "FuncApp",
    "Ident",
    "NumberLit",
    "UnaryNeg",
    "emit_lean",
    "StateManager",
    "AxleConnectionError",
    "AxleConnectionResetError",
    "AxleError",
    "AxleInvalidArgumentError",
    "AxleNonTransientError",
    "AxleRateLimitedError",
    "AxleRetriesExhaustedError",
    "AxleTimeoutError",
    "AxleTransientError",
    "AxleUnavailableError",
    "AxleValidationError",
    "BudgetExhaustedError",
    "ExpressionParseError",
    "FormalConstructError",
    "MissingApiKeyError",
    "ScaffoldingError",
    "SchemaExtractionError",
    "SchemaRollbackRequested",
    "UnknownDomainError",
    "UnsupportedCompositionError",
    "UnsupportedDomainError",
    "log_axle_call",
    "log_phase_duration",
    "log_repair_stats",
    "log_termination",
    "sanitize_log_value",
    "timed",
]
